apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    pod-template-hash: 7fb96c846b
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    pod-template-hash: 7fb96c846b
  type: NodePort
status:
  loadBalancer: {}
