apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Remplacez par l'étiquette appropriée utilisée dans votre déploiement NGINX
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Vous pouvez également utiliser NodePort si nécessaire

