apiVersion: apps/v1
kind: Deployment
metadata:
  name: startkit-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-startkit
  template:
    metadata:
      labels:
        app: backend-startkit
    spec:
      containers:
      - name: backend-startkit
        image: infras/starterkit:0.1.96-starterkit-api
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-startkit
  name: startkit-backend-service
spec:
  type: NodePort
  ports:
    - name: startkit-backend-port
      port: 9080
      nodePort: 30085 
      targetPort: 9080
  selector:
    app: backend-startkit

